#logfile
filebeat.inputs:
  - type: filestream
    id: {{ component }} #check in all comp in vars
    enabled: true
    paths:
      - {{log_file}} #check in frontend vars

fields:
  component: {{component}}
#if we keep field  then only the frntend name will come in elastic
  #though we keep in 'id'

 # Logstash Output
output.logstash:
  hosts: ["172.31.13.214:5044"] #elk instance pri-ip has to give

  #Default
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
   # few logs steps will delete
#processors:
#  - add_host_metadata:
#      when.not.contains.tags: forwarded
#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~
#  - add_kubernetes_metadata: ~

