- name: import nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: java
    #func_nodejs instead of call func here ansible call

    # component=shipping   #in vars/dispatch.service
    # schma_check=mysql    #in vars/dispatch.service
    # func_nodejs  # here only
