- name: Install yum nginx
  ansible.builtin.yum:
    name: nginx
    state: installed  # check the install ,update ,remove

- name: copy roboshop confg file
  ansible.builtin.template:
    src: roboshop.conf # no need to keep total path as like shell
    dest: /etc/nginx/default.d/roboshop.conf
  # if only web-server checking then keep all application to localhost.

# in elk this step in log msg to get required format
- name: copy nginx confg
  ansible.builtin.template:
    src: nginx.conf # no need to keep total path as like shell
    dest: /etc/nginx/nginx.conf

 # in shell we are removing only data &  download & un-zip content
 # but here we are deleting folder & creating
- name: remove default data
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent # to removed (or) absent

- ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory # to create directory folder mkdir

- name: download roboshop file and extract
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip #instead of curl and rename
    dest: /usr/share/nginx/html #un-zip file path
    remote_src: yes   #Unarchive will help to deal with url and get file , to do this Remote_src is imp

- name: to restart the systemd
  ansible.builtin.systemd:
    name: nginx
    state: restarted  #systemctl restart nginx
    enabled: yes      #systemctl enable nginx

- name: import nodejs
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat