[Unit]
  Description = Dispatch Service
  [Service]
  User=roboshop
  Environment=AMQP_HOST={{ lookup('aws_ssm','dev.frontend.payment_AMQP_HOST',region='us-east-1') }}
  Environment=AMQP_USER={{ lookup('aws_ssm','dev.frontend.payment_AMQP_USER',region='us-east-1') }}
  Environment=AMQP_PASS={{ lookup('aws_ssm','dev.frontend.payment_AMQP_PASS',region='us-east-1') }}
  ExecStart=/app/dispatch
  SyslogIdentifier=dispatch
  
  [Install]
  WantedBy=multi-user.target
  
