# labauto prometheus-server this is not compulsory step
- name: install prometheus
  ansible.builtin.shell : labauto prometheus-server

- name: copy logstash confg
  ansible.builtin.template:
    src: "{{item}}.yml"
    dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - alerts

- name: install systemd
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
#    enabled: true   # to main uniform true is keeping all

  #check the port 9090 is coming (or) not