#- name: install prometheus
#  ansible.builtin.shell : labauto prometheus-server

- name: copy logstash confg
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: install systemd
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
#    enabled: true   # to main uniform true is keeping all
