- name:
  ansible.builtin.user:
    name: "{{username}}" #this is common for all comp ,so keep in common/vars

- name: remove default data
  ansible.builtin.file:
    path: /app
    state: absent # to removed (or) absent

- ansible.builtin.file:
    path: /app
    state: directory # to create directory  mkdir

#- name: download roboshop file and extract
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip #instead of curl and rename
#    dest: /app  #un-zip file path
#    remote_src: yes   #Unarchive will help to deal with url and get file ,to do this Remote_src is imp


- name: download roboshop file and extract
  ansible.builtin.unarchive:
    src: http://172.31.81.221:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app  #un-zip file path
    remote_src: yes   #Unarchive will help to deal with url and get file ,to do this Remote_src is imp
