- name: install maven
  ansible.builtin.yum:
    name: maven
    state: installed  #-y not required in ansible
# (or)
#- name: install maven
#  ansible.builtin.shell: dnf install maven -y

- name: import app_pre
  ansible.builtin.import_tasks:
    file: app_pre.yml

- name: install npm
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app
# check upto npm in linux by  cd /app  ls-l   cat package.json [ no error has to get ]

#step-2
- name: import tasks data
  ansible.builtin.import_tasks:
    file: schema.yml

#step-3  find . name "*catalogue.service*"  cd /etc/systemd/system ls -l  vim catalogue.service [ .service is mandatory ]
- name: import systemd
  ansible.builtin.import_tasks:
    file: systemd.yml

# tail -f /var/log/messages