#  print_head "install nodejs"
#  dnf module disable nodejs -y &>>${log_path}
#  dnf module enable nodejs:18 -y &>>${log_path}

#  dnf install nodejs -y &>>${log_path}
#  func_exit $?

#  print_head "library install"
#  cd /app &>>${log_path}
#  npm install &>>${log_path}
#  func_exit $?

#  print_head "install systemd"
#  cp $script_path/${component}.systemd  /etc/systemd/system/${component}.service &>>${log_path}
#  func_exit $?

#  systemctl daemon-reload &>>${log_path}
#  systemctl enable ${component} &>>${log_path}
#  systemctl restart ${component} &>>${log_path}
#  func_exit $?

- name: install disable of nodejs
  ansible.builtin.shell : dnf module disable nodejs

- name: install enable of nodejs
  ansible.builtin.shell : dnf module enable nodejs>18

 # ansible.builtin.shell: curl -sL https://rpm.nodesoure.com/setup_lts.x | bash

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed  # check the install ,update ,remove

- name: import tasks data
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: install npm
  ansible.builtin.shell: npm install
  args:
    chdir: /app
