#- name: install disable of nodejs -y
#  ansible.builtin.shell : dnf module disable nodejs -y # for shell command -y has to keep in ansible
#
#- name: install enable of nodejs
#  ansible.builtin.shell : dnf module enable nodejs:18 -y
#
#- name: Install nginx #  cd /etc/yum.repos.d  ls [why not this]
#  ansible.builtin.yum:
#    name: nodejs
#    state: installed  # check the install ,update ,remove

 - name: config nodejs repo  #  cd /etc/yum.repos.d  ls
   ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: import tasks data
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: install npm
  ansible.builtin.shell: npm install
  args:
    chdir: /app
 # check upto npm in linux by  cd /app  ls-l   cat package.json [ no error has to get ]

#step-2
- name: import tasks data
  ansible.builtin.import_tasks:
    file: schema.yml

#step-3  find . name "*catalogue.service*"  cd /etc/systemd/system ls -l  vim catalogue.service [ .service is mandatory ]
- name: import systemd
  ansible.builtin.import_tasks:
    file: systemd.yml

# tail -f /var/log/messages