- name: install disable of nodejs -y
  ansible.builtin.shell : dnf module disable nodejs -y # for shell command -y has to keep in ansible

- name: install enable of nodejs
  ansible.builtin.shell : dnf module enable nodejs:18 -y
 # ansible.builtin.shell: curl -sL https://rpm.nodesoure.com/setup_lts.x | bash

- name: Install nginx
  ansible.builtin.yum:
    name: nodejs
    state: installed  # check the install ,update ,remove

- name: import tasks data
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: install npm
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: import tasks data
  ansible.builtin.import_tasks:
    file: schema.yml

- name: import systemd
  ansible.builtin.import_tasks:
    file: systemd.yml