#print_head  "install python"
#dnf install python36 gcc python3-{{env}}el -y &>>${log_path}

#print_head  "install library"
#cd /app &>>${log_path}
#pip3.6 install -r requirements.txt &>>${log_path}

##roboshop123
#print_head  "install systemd"
#sed -i -e "s|rabbitm1_lg_password2|${rabbitm1_lg_password}|" ${script_path}/${component_pay}.systemd &>>${log_path}

#cp ${script_path}/${component_pay}.systemd  /etc/systemd/system/${component_pay}.service &>>${log_path}
#systemctl daemon-reload  &>>${log_path}
#systemctl enable ${component_pay} &>>${log_path}
#systemctl restart ${component_pay} &>>${log_path}

- name: Install python #  cd /etc/yum.repos.d  ls [why not this]
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed  # check the install ,update ,remove

- name: import tasks data
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: install python dependences
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app
 #check upto npm in linux by  cd /app  ls-l   cat package.json [ no error has to get ]

#step-2
#- name: import tasks data
#  ansible.builtin.import_tasks:
#    file: schema.yml

#step-3  find . name "*catalogue.service*"  cd /etc/systemd/system ls -l  vim catalogue.service [ .service is mandatory ]
- name: import systemd
  ansible.builtin.import_tasks:
    file: systemd.yml

- name: import promtheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_expo