#- name: copy ansible file
#  ansible.builtin.copy:
#    src: mongo.repo
#    dest: /etc/yum.repos.d/mongo.repo
#  when: schema == "mongo"
#
#- name: install mongodb client
#  ansible.builtin.yum:
#    name: mongodb-org-shell
#    state: installed
#  when: schema == "mongo"
#
#- name: load schema
#  ansible.builtin.shell: mongo --host {{ lookup('aws_ssm','{{env}}.frontend.catalogue_mongoendpoint',region='us-east-1') }} </app/schema/{{component}}.js
#  when: schema == "mongo"

- name: loading mongo schema
  when: schema == "mongo"
  block:
    - name : copy ansible file
      ansible.builtin.copy:  # to get the file from files use copy
        src: mongo.repo       # no need to write total path like shell
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell # in yum no need -y
        state: installed

    - name : Download DOCPEM file  # this is for seure connection btw catalogue & DOCDB
      ansible.builtin.get_url:  # to get the file from files use copy
        url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem

    - name: load schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm','{{env}}.{{component}}.mongo_endpoint',region='us-east-1') }} </app/schema/{{component}}.js

#------------#shipping-mysql------------------#
# - my sql repo was not kept  bcz in shipping.sh it is thy in document
#dnf install mysql -y &>>${log_path}
#RoboShop@1 --password as input
#mysql -h mysql.{{env}}ops72bat.online -uroot -p${mysqlpassword} < /app/schema/${component_shp}.sql &>>${log_path}

- name: loading mysql schema
  when: schema == "mysql"
  block:
    - name : install mysql
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: load schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm','{{env}}.{{component}}.db_host',region='us-east-1') }} -u{{ lookup('aws_ssm','{{env}}.shipping.user',region='us-east-1') }} -p{{ lookup('aws_ssm','{{env}}.shipping.password',region='us-east-1') }} < /app/schema/{{component}}.sql


#------------#payment-rabbitmq------------------#
 #  rabbit mq file was not kept in schema
















