#- name: copy ansible file
#  ansible.builtin.copy:
#    src: mongo.repo
#    dest: /etc/yum.repos.d/mongo.repo
#  when: schema == "mongo"
#
#- name: install mongodb client
#  ansible.builtin.yum:
#    name: mongodb-org-shell
#    state: installed
#  when: schema == "mongo"
#
#- name: load schema
#  ansible.builtin.shell: mongo --host {{ lookup('aws_ssm','dev.frontend.catalogue_mongoendpoint',region='us-east-1') }} </app/schema/{{component}}.js
#  when: schema == "mongo"

- name: loading mongo schema
  when: schema == "mongo"
  block:
    - name : copy ansible file
      ansible.builtin.copy:  # to get the file from files use copy
        src: mongo.repo       # no need to write total path like shell
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell # in yum no need -y
        state: installed

    - name: load schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm','dev.frontend.catalogue_mongoendpoint',region='us-east-1') }} </app/schema/{{component}}.js

#------------#shipping-mysql------------------#
# - my sql repo was not kept  bcz in shipping.sh it is thy in document
#dnf install mysql -y &>>${log_path}
#RoboShop@1 --password as input
#mysql -h mysql.devops72bat.online -uroot -p${mysqlpassword} < /app/schema/${component_shp}.sql &>>${log_path}

- name: loading mysql schema
  when: schema == "mysql"
  block:
    - name : install mysql
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: load schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm','dev.frontend.shipping_db_host',region='us-east-1') }} -u{{ lookup('aws_ssm','dev.frontend.shipping_user',region='us-east-1') }} -p{{ lookup('aws_ssm','dev.frontend.shipping_password',region='us-east-1') }} < /app/schema/{{component}}.sql

#------------#payment-rabbitmq------------------#
 #  rabbit mq file was not kept in schema
- name: loading rabbitmq schema
  when: schema == "rabbitmq"
  block:
    - name: load schema
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: load schema
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: install rabbitmq
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed

    - name: install {{component}} systemd
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: restarted
        enabled: true   # to main uniform true is keeping all

    - name: add application user
      community.rabbitmq.rabbitmq_user:
         user: roboshop
         password: roboshop123
         vhost: /
         configure_priv: .*
         read_priv: .*
         write_priv: .*
         state: present















