groups:
- name: High-Cpu-Utlization-ec2-nodes
  rules:
  - alert: High-Cpu-Utlization
    expr: 100 - ( avg by (component ,env ,instance ,job ,name) (rate(node_cpu_seconds_total{mode="idle"}[1m]) *100)) > 50
    for: 1m
    labels:
      severity: page
    annotations:
      summary: High Cpu usage

  - alert: High-memory-Utlization
    expr: 100 - ( 100 * ( (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) /node_memory_MemTotal_bytes )) > 50
    for: 1m
    labels:
      severity: page
    annotations:
      summary: High memory usage

  - alert: serverdown
    expr: up < 1
    for: 1m
    labels:
      severity: page
    annotations:
      summary: server-down

  {% for component in components %}
   # space compuslaory
  - alert: systemd-{{ component }}
    expr: node_systemd_unit_state{component="{{component.name}}",exported_name="{{component.service_name}}.service", state="active"} <1
    for: 1m
    labels:
      severity: page
    annotations:
      summary: systemd-check
  {%- endfor %}
