groups:
- name: ec2-nodes
  rules:
  - alert: High-Cpu-Utlization
    expr: 100 - ( avg by (component ,env ,instance ,job ,name) (rate(node_cpu_seconds_total{mode="idle"}[1m]) *100)) > 50
    for: 1m
    labels:
      severity: page
    annotations:
      summary: High Cpu usage