# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # dynamic_configs
  - job_name: "ec2-nodes"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:  # link for tags in local.tf
          - name: tag:Monitor
            values: [ "true" ]

  #this is link btw prometheus & nodeexpo
  # static_configs
  #- job_name: "ec2-nodes"
  #  static_configs:
  #    - targets: ["172.31.40.130:9100"]
